name: Job Alert Bot

on:
  schedule:
    - cron: '0 7 */3 * *'  # Runs every 3 days at 7:00 AM
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  run-job-alert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v1
      with:
        chrome-version: 'latest'

    - name: Run the Job Alert Bot
      env:
        SCRAPE_URL: ${{ secrets.SCRAPE_URL }}
        API_KEY: ${{ secrets.API_KEY }}
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
      run: |
        python NYFA_jobalerts.py
