name: Job Alert Bot

on:
  schedule:
    - cron: '0 7 */3 * *'  # Runs every 3 days at 7:00 AM
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  run-job-alert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python and Pip
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        python3 --version
        pip3 --version

    - name: Run Job Alert Bot in Docker
      uses: docker://selenium/standalone-chrome:latest
      with:
        args: >
          sh -c "pip install -r requirements.txt &&
                 python NYFA_jobalerts.py"
      env:
        SCRAPE_URL: ${{ secrets.SCRAPE_URL }}
        API_KEY: ${{ secrets.API_KEY }}
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
