name: Job Alert Bot

on:
  schedule:
    - cron: '0 7 */3 * *'  # Runs every 3 days at 7:00 AM
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  run-job-alert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Job Alert Bot in Docker
      uses: docker://joyzoursky/python-chromedriver:3.9-selenium
      with:
        args: >
          sh -c "pip install -r requirements.txt &&
                 python your_script.py"
      env:
        SCRAPE_URL: ${{ secrets.SCRAPE_URL }}
        API_KEY: ${{ secrets.API_KEY }}
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
